version: "3"

services:
  spring:
    build: 
      context: ../../
      dockerfile: ./.docker/app/Dockerfile
    container_name: spring-container
    ports:
      - "8080:8080"
    extra_hosts:
      - "localhost:127.0.0.1"