version: 2
updates:
  - package-ecosystem: "gradle"
    directories: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "dependabot"
    target-branch: "feature_develop"